apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
  labels: 
    app: webserver
    tier: frontend
    region: IN
spec: 
  containers: 
  - name: httpd-con
    image: vimal13/apache-webserver-php



